### ISSUE TITLE
the url  "http://127.0.0.1:8080/rest/hello" is not match for jersy-jetty

### ISSUE THREAD

**Issue by kingsmiler** [smallnest/Jax-RS-Performance-Comparison#1]
I use "http://127.0.0.1:8080/rest/hello" to access and I got a 404.

I checked the file HelloResource, it's just "hello" only.
jersey-jetty\src\main\java\com\colobu\rest\jerseyjetty\HelloResource.java

BTW, when using jetty with version 9.3.8.v20160314, there is a NoSuchMethod exception broken out.

**Comment by smallnest** [comment]
visit "http://127.0.0.1:8080/hello" instead of "http://127.0.0.1:8080/rest/hello"
